# application-docker.yml

spring:
  datasource:
    url: jdbc:postgresql://postgres_container:5432/test_db
    username: test_user
    password: test_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
