version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - spring-postgres-network

  spring-app:
    image: ilsosnin/learning_repo:latest
    container_name: spring_app_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    networks:
      - spring-postgres-network

networks:
  spring-postgres-network:
    driver: bridge
