openapi: 3.0.0
info:
  title: Simple Learning API
  description: A simple API for learning
  version: 1.0.0

paths:
  /user/{user_id}:
    get:
      summary: Get user info
      operationId: getUser
      tags:
        - User
      parameters:
        - name: user_id
          in: path
          description: User UUID to get
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /user/create:
    post:
      tags:
        - User
      description: Create new User
      operationId: createUser
      requestBody:
        description: Create new User body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'

      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /subscription:
    get:
      summary: Get all subscriptions list
      operationId: getSubscriptions
      tags:
        - Subscription
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SubscriptionInfo'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /subscription/{subscription_id}:
    get:
      summary: Get all subscriptions list
      operationId: getSubscriptionById
      tags:
        - Subscription
      parameters:
        - name: subscription_id
          in: path
          description: Subscription UUID to get
          required: true
          schema:
            type: string
            format: UUID
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionInfo'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /trainings:
    get:
      summary: Get all trainings list
      operationId: getTrainings
      tags:
        - Trainings
      parameters:
        - name: date
          in: query
          schema:
            type: string
          example: "2022-07-24"
          required: true
        - name: subscription_level
          in: query
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Training'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /trainings/{training_id}:
    get:
      summary: Get training info
      operationId: getTrainingInfo
      tags:
        - Trainings
      parameters:
        - name: training_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

  /trainings/create:
    post:
      summary: Creates a training
      operationId: createTraining
      tags:
        - Trainings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTraining'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
        '400':
          $ref: '#/api-errors.yaml#/BadRequest'
        '401':
          $ref: '#/api-errors.yaml#/Unauthorized'
        '500':
          $ref: '#/api-errors.yaml#/InternalServerError'

components:
  schemas:
    UserInfo:
      type: object
      properties:
        id:
          type: string
          format: UUID
        email:
          type: string
        subscription:
          $ref: '#/components/schemas/SubscriptionInfo'
        registration_date:
          type: string
          format: date
      required:
        - id
        - email
        - subscription
        - registration_date

    CreateUserRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        subscription_id:
          type: string
      required:
        - name
        - email
        - subscription_id

    SubscriptionInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        subscription_level:
          type: integer
        type:
          type: string
          enum:
            - FREE
            - S
            - M
            - L
            - XL
      required:
        - id
        - name
        - subscription_level
        - type

    CreateTraining:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
          example: "2024-07-24"
        type:
          type: string
          enum:
            - POOOOWER
            - Yoga
            - Chilling
        required_level:
          description: Minimal required subscription level to attend this class
          type: int
      required:
        - name
        - type
        - required_level

    Training:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        date:
          type: string
          example: "2024-07-24"
        type:
          type: string
          enum:
            - POOOOWER
            - Yoga
            - Chilling
        required_level:
          description: Minimal required subscription level to attend this class
          type: int
      required:
        - id
        - name
        - type
        - required_level