openapi: 3.0.0
info:
  title: Simple Learning API
  description: A simple API for learning
  version: 1.0.0

paths:
  /hello:
    get:
      summary: Test
      operationId: getHello
      tags:
        - Hello
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldApiResponse'
  /send:
    get:
      summary: Just a bit of trolling
      operationId: getMeme
      tags:
        - memes
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelloWorldApiResponse'
  /hello/all:
    get:
      summary: Test
      operationId: getAllHello
      tags:
        - Hello
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HelloWorldApiResponse'


components:
  schemas:
    HelloWorldApiResponse:
      type: object
      properties:
        value:
          type: string