name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VPS
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          ssh -o StrictHostKeyChecking=no $VPS_USER@$VPS_HOST -p $VPS_SSH_PORT << 'EOF'
            docker pull ilsosnin/learning_repo:latest
            docker stop learning_repo_container || true
            docker rm -f learning_repo_container
            docker run -d --name learning_repo_container -p 9000:8080 ilsosnin/learning_repo:latest
          EOF
